/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/*
 * CAN1:
 * 	Baudrate: 500bit; Clock 16Mhz
 * 	Seg1 (Prop_seg + Phase_Seg1): 13, Seg2: 2;
 * 	Number of Tq: 16
 * 	APB1
 * 	ALT9
 * 	Tx: PD1
 * 	Rx: PD0
 */

#define AHB1PERIPH_BASEADDR 0x40020000U
#define APB1PERIPH_BASEADDR 0x40000000U
#define GPIOA_BASEADDR (AHB1PERIPH_BASEADDR) // GPIOA
#define GPIOB_BASEADDR 0x40020400U					 // GPIOB
#define GPIOD_BASEADDR 0x40020C00U					 // GPIOD
#define CAN1_BASEADDR (0x40006400U)					 // CAN1
#define RCC_BASEADDR (0x40023800U)					 // RCC

void Init_CANPin(void)
{
	uint32_t temp = 0;
	*(uint32_t *)(RCC_BASEADDR + 0x30) |= (1 << 3); // Enable GPIOD
	temp = (2 << 0) | (2 << 2);
	*((uint32_t *)(GPIOD_BASEADDR + 0x00)) |= temp; // Set Mode: Alternate Function
	temp = (9 << 0) | (9 << 4);
	*((uint32_t *)(GPIOD_BASEADDR + 0x20)) |= temp; // Select Alternate Function 9
	temp = (2 << 0) | (2 << 2);
	*((uint32_t *)(GPIOD_BASEADDR + 0x08)) |= temp; // Select speed
}

void Init_CANFilter(void)
{
	*(uint32_t *)(CAN1_BASEADDR + 0x200) |= (1 << 0);
	*(uint32_t *)(CAN1_BASEADDR + 0x21C) &= ~(1 << 0);
	*(uint32_t *)(CAN1_BASEADDR + 0x20C) |= (1 << 0);
	*(uint32_t *)(CAN1_BASEADDR + 0x240) = 0xFFFFFFFF;
	*(uint32_t *)(CAN1_BASEADDR + 0x244) = 0x00000000;
	*(uint32_t *)(CAN1_BASEADDR + 0x21C) |= (1 << 0);
	*(uint32_t *)(CAN1_BASEADDR + 0x200) &= ~(1 << 0);
}

void Init_CAN(void)
{
	*(uint32_t *)(RCC_BASEADDR + 0x40) |= (1 << 25); // Enable CAN1

	/* Reset CAN */
	*(uint32_t *)(CAN1_BASEADDR) |= (1 << 15); /* Set RESET bit*/
	// while (!((*(uint32_t*)(CAN1_BASEADDR) >> 15) && 0x1));	/* Wait RESET complete MCR_RESET*/
	while ((*(uint32_t *)(CAN1_BASEADDR) & (1 << 15)))
		;

	/* Set mode initialize */
	*(uint32_t *)(CAN1_BASEADDR) |= (1 << 0); /* Set Initialize Request */
	while (!((*(uint32_t *)(CAN1_BASEADDR + 0x04)) & 0x1))
		; /* Wait Initialize complete MSR_INAK */

	/* Exit sleep mode */
	*(uint32_t *)(CAN1_BASEADDR) &= ~(1 << 1);
	while (((*(uint32_t *)(CAN1_BASEADDR + 0x04)) & 0x2))
		;

	/* Set bit timing + loop back mode*/
	*(uint32_t *)(CAN1_BASEADDR + 0x1C) = 0x401C0001;

	Init_CANFilter();

	/* Exit mode Initialize */
	*(uint32_t *)(CAN1_BASEADDR) &= ~(1 << 0); /* Set Exit Initialize mode */
	while ((*(uint32_t *)(CAN1_BASEADDR + 0x04) & 0x1))
		; /* Wait Exit Initialize mode complete MSR_INAK */
}

void CAN_Tx(uint8_t msg[])
{
	uint32_t TDTR, TIR, TDLR, TDHR;
	uint32_t Box_empty;
	uint32_t Box1_State, Box2_State, Box0_State;

	Box0_State = ((*(uint32_t *)(CAN1_BASEADDR + 0x08) >> 26) & 0x01);
	Box1_State = ((*(uint32_t *)(CAN1_BASEADDR + 0x08) >> 27) & 0x01);
	Box2_State = ((*(uint32_t *)(CAN1_BASEADDR + 0x08) >> 28) & 0x01);

	/* Check that all the Tx mailboxes are not full */
	if (Box0_State || Box1_State || Box2_State)
	{
		/* Select an empty transmit mailbox */
		Box_empty = ((*(uint32_t *)(CAN1_BASEADDR + 0x08) >> 24) & 0x3);

		if (Box_empty == 0)
		{
			TIR = 0x180;
		}
		else if (Box_empty == 1)
		{
			TIR = 0x190;
		}
		else if (Box_empty == 2)
		{
			TIR = 0x1A0;
		}
		TDTR = TIR + 0x4;
		TDLR = TIR + 0x8;
		TDHR = TIR + 0xC;
		/* Set ID */
		uint32_t tempTIR = (0x1D << 21);
		*(uint32_t *)(CAN1_BASEADDR + TIR) = tempTIR;

		/* Set DLC */
		tempTIR = (5 << 0);
		*(uint32_t *)(CAN1_BASEADDR + TDTR) = tempTIR;

		/* Set up the data field */
		*(uint32_t *)(CAN1_BASEADDR + TDLR) = msg[0] | (msg[1] << 8) | (msg[2] << 16) | (msg[3] << 24);
		*(uint32_t *)(CAN1_BASEADDR + TDHR) = msg[4];

		/* Request transmission */
		*(uint32_t *)(CAN1_BASEADDR + TIR) |= (1 << 0);
	}
}



void CAN_Rx(uint8_t msg[], uint32_t *ID, uint32_t *DLC)
{
	while (*(uint32_t *)(CAN1_BASEADDR + 0x0C) & 0x2)
		;
	*ID = ((*(uint32_t *)(CAN1_BASEADDR + 0x1B0) >> 21) & 0x7FF);
	*DLC = (*(uint32_t *)(CAN1_BASEADDR + 0x1B4) & 0xF);
	msg[0] = (*(uint32_t *)(CAN1_BASEADDR + 0x1B8) & 0XFF);
	msg[1] = ((*(uint32_t *)(CAN1_BASEADDR + 0x1B8) >> 8) & 0XFF);
	msg[2] = ((*(uint32_t *)(CAN1_BASEADDR + 0x1B8) >> 16) & 0XFF);
	msg[3] = ((*(uint32_t *)(CAN1_BASEADDR + 0x1B8) >> 24) & 0XFF);
	msg[4] = (*(uint32_t *)(CAN1_BASEADDR + 0x1BC) & 0XFF);

	*(uint32_t *)(CAN1_BASEADDR + 0x0C) |= (1 << 5);
}

int main(void)
{
	uint8_t msg[5] = {'H', 'E', 'L', 'L', 'O'};
	uint32_t ID, DLC;
	uint8_t msgRx[5];
	Init_CANPin();
	Init_CAN();

	/* Loop forever */
	while (1)
	{
		CAN_Tx(msg);
		for (uint32_t i = 0; i < 100000; i++)
			;
		CAN_Rx(msgRx, &ID, &DLC);
		for (uint32_t i = 0; i < 100000; i++)
			;
	}
}
